---
# Global defaults; override in inventory vars if needed
essential_packages:
  - curl
  - python3
  - vim
  - git

admin_username: ansible
local_ssh_public_key_path: "~/.ssh/id_rsa.pub"

# Docker flags
install_docker: false
install_docker_compose: true
docker_verify_installation: true
docker_run_hello_world_test: true
docker_compose_test: true

# Tailscale flags
install_tailscale: false
tailscale_advertise_routes: false
tailscale_advertised_routes: []
tailscale_exit_node: true
tailscale_accept_routes: true
tailscale_ssh: true
tailscale_reset: false

tailscale_auth_key: "{{ vault_tailscale_auth_key | default('') }}"

